databases:
  - name: kavajo-db
    plan: free
    databaseName: kavajo
    user: kavajo_user

services:
  - type: web
    plan: free
    name: kavajo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sistema.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kavajo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
