# Generated by Django 5.1.1 on 2024-11-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('administrador', 'Administrador'), ('vendedor', 'Vendedor')], max_length=20),
        ),
    ]
