# Generated by Django 5.1.1 on 2024-11-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_userrole_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'Rol de Usuario', 'verbose_name_plural': 'Roles de Usuario'},
        ),
    ]
