# Generated by Django 5.1.1 on 2024-09-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del cliente', max_length=255)),
                ('curp', models.CharField(help_text='Clave Única de Registro de Población (CURP)', max_length=100, unique=True)),
                ('nss', models.CharField(help_text='Número de Seguridad Social (NSS)', max_length=100, unique=True)),
                ('direccion', models.TextField(help_text='Dirección completa del cliente')),
                ('colonia', models.CharField(help_text='Colonia de residencia del cliente', max_length=255)),
                ('referencias', models.TextField(blank=True, help_text='Referencias personales del cliente', null=True)),
                ('fotografia', models.ImageField(blank=True, help_text='Fotografía del cliente', null=True, upload_to='clientes/fotos/')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del cliente en el sistema')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
