# Generated by Django 5.1.1 on 2024-09-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, help_text='Apellido materno del cliente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(blank=True, help_text="Apellido's Paterno del cliente", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='Fotografía del cliente', null=True, upload_to='clientes/fotos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text="Nombre's del cliente", max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='referencias',
            field=models.TextField(blank=True, help_text='Referencias personales del cliente', null=True, verbose_name='referencia'),
        ),
    ]
