# Generated by Django 5.1.1 on 2024-09-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_apellido_materno_cliente_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(blank=True, help_text='Apellido Paterno del cliente', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
