# Generated by Django 5.1.1 on 2024-10-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Vendedor', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='referencias',
        ),
        migrations.AddField(
            model_name='cliente',
            name='alta',
            field=models.CharField(blank=True, help_text='Alta', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_de_baja',
            field=models.DateField(blank=True, help_text='Fecha de Baja', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_de_firma',
            field=models.TextField(blank=True, help_text='Fecha de Firma', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_para_capturar_retiro',
            field=models.DateField(blank=True, help_text='Fecha para capturar retiro', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del cliente', null=True, verbose_name='referencia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rcv',
            field=models.CharField(blank=True, help_text='RCV', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text='Numero de telefono del cliente', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(help_text='Vendedor al que pertenece el cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vendedor'),
        ),
    ]
