# Generated by Django 5.1.1 on 2024-10-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_fecha_de_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_baja',
            field=models.TextField(blank=True, help_text='Fecha de Baja', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre del cliente', max_length=255),
        ),
    ]
