# Generated by Django 5.1.1 on 2024-10-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_fecha_de_baja_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_baja',
            field=models.DateField(blank=True, help_text='Fecha de Baja', null=True),
        ),
    ]
