# Generated by Django 5.1.1 on 2024-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_fecha_de_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones del cliente', null=True, verbose_name='observaciones'),
        ),
    ]
