# Generated by Django 5.1.1 on 2024-10-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_observaciones_alter_vendedor_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(help_text='Número de la semana (1-52)')),
                ('fecha_de_pago', models.DateField(blank=True, null=True)),
                ('cancelacion', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.vendedor')),
            ],
        ),
    ]
