# Generated by Django 5.1.1 on 2024-10-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_semanacliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemanaCliente',
            new_name='Pago',
        ),
    ]
