# Generated by Django 5.1.1 on 2024-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_pago_cancelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cancelacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
