# Generated by Django 5.1.1 on 2024-10-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_pago_cancelacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
    ]
