# Generated by Django 5.1.1 on 2024-10-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_cliente_observaciones'),
        ('clientes', '0014_alter_pago_cancelacion'),
    ]

    operations = [
    ]
