# Generated by Django 5.1.1 on 2024-10-26 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0015_alter_vendedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='colonia',
            field=models.CharField(blank=True, help_text='Colonia de residencia del cliente', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección completa del cliente', null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_baja',
            field=models.CharField(blank=True, help_text='Fecha de Baja', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_firma',
            field=models.CharField(blank=True, help_text='Fecha de Firma', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_para_capturar_retiro',
            field=models.CharField(blank=True, help_text='Fecha para capturar retiro', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Vendedor al que pertenece el cliente', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.vendedor'),
        ),
    ]
