# Generated by Django 5.1.1 on 2024-10-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_cliente_colonia_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='_46dias',
            field=models.DateField(blank=True, null=True),
        ),
    ]
