# Generated by Django 5.1.1 on 2024-10-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_pago__46dias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='_46dias',
            new_name='F46dias',
        ),
    ]
