# Generated by Django 5.1.1 on 2024-10-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_rename__46dias_pago_f46dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_de_firma',
            field=models.DateField(blank=True, help_text='Fecha de Firma (DD/MM/YYYY)', null=True),
        ),
    ]
