# Generated by Django 5.1.1 on 2024-11-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0021_alter_telefono_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
