# Generated by Django 5.1.1 on 2024-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0022_alter_telefono_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='anticipo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
