# Generated by Django 5.1.1 on 2024-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0023_alter_pago_anticipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='F46dias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
