# Generated by Django 5.1.1 on 2024-11-03 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0024_alter_pago_f46dias_alter_pago_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
