# Generated by Django 5.1.1 on 2024-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0025_alter_pago_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cambio_de_afore',
            field=models.CharField(blank=True, choices=[('no_necesario', 'No necesario'), ('necesario', 'Necesario'), ('pendiente', 'Pendiente')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_aval',
            field=models.ImageField(blank=True, help_text='Fotografia del Aval', null=True, upload_to='clientes/fotos/', verbose_name='Foto'),
        ),
    ]
