# Generated by Django 5.1.1 on 2024-11-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0029_alter_vendedor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cambio_de_afore',
            field=models.CharField(blank=True, choices=[('no_necesario', 'No necesario'), ('listo', 'Listo'), ('pendiente', 'Pendiente')], max_length=20, null=True),
        ),
    ]
